<?php

declare(strict_types=1);

namespace App\Tests\Doctrine;

use App\Doctrine\ProductionIndexNameListener;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Tools\Event\GenerateSchemaEventArgs;
use PHPUnit\Framework\TestCase;

final class ProductionIndexNameListenerTest extends TestCase
{
    public function testItAppliesProductionNamesToJoinTableIndexes(): void
    {
        $schema = new Schema();
        $table = $schema->createTable('cardnext_cms_download_channel');
        $table->addColumn('cms_download_id', 'integer');
        $table->addColumn('channel_id', 'integer');
        $table->setPrimaryKey(['cms_download_id', 'channel_id']);
        $table->addIndex(['channel_id'], 'IDX_AUTOGENERATED');

        $listener = new ProductionIndexNameListener();
        $listener->postGenerateSchema(new GenerateSchemaEventArgs(
            $this->createStub(EntityManagerInterface::class),
            $schema,
        ));

        self::assertTrue($table->hasIndex('idx_cms_dc_download'));
        self::assertSame(['cms_download_id'], $table->getIndex('idx_cms_dc_download')->getColumns());
        self::assertTrue($table->hasIndex('idx_cms_dc_channel'));
        self::assertSame(['channel_id'], $table->getIndex('idx_cms_dc_channel')->getColumns());
        self::assertFalse($table->hasIndex('IDX_AUTOGENERATED'));
    }
}
