<?php

declare(strict_types=1);
namespace App\Controller\Shop;
use App\Entity\Customer\Customer; use App\Entity\Quote\QuoteRequest; use App\Form\Type\Quote\QuoteRequestType; use App\Service\Quote\{QuoteCartService,QuoteRequestMailer,QuoteRequestSubmitter}; use Sylius\Component\Channel\Context\ChannelContextInterface; use Sylius\Component\Core\Model\ChannelInterface; use Symfony\Bundle\FrameworkBundle\Controller\AbstractController; use Symfony\Component\HttpFoundation\{Request,Response}; use Symfony\Component\Routing\Attribute\Route; use Symfony\Component\Uid\Uuid;
final class QuoteCartController extends AbstractController {public function __construct(private QuoteCartService $cart,private ChannelContextInterface $channels){}
 #[Route('/{_locale}/angebotskorb',name:'cardnext_shop_quote_cart',methods:['GET','POST'],priority:200)] public function index(Request $request,QuoteRequestSubmitter $submitter,QuoteRequestMailer $mailer):Response{$channel=$this->channel();$items=$this->cart->resolvedItems($channel);$quote=new QuoteRequest();$user=$this->getUser();if(method_exists($user??new \stdClass(),'getCustomer')&&($customer=$user->getCustomer()) instanceof Customer){$quote->setCustomer($customer);$quote->setEmail($customer->getEmail() ?? '');$quote->setContactName(trim(($customer->getFirstName() ?? '').' '.($customer->getLastName() ?? '')));}$form=$this->createForm(QuoteRequestType::class,$quote);$form->handleRequest($request);if($form->isSubmitted()&&$form->isValid()&&''===$form->get('website')->getData()&&[]!==$items){$token=(string) ($request->request->all('quote_request')['_submission'] ?? '');$storedToken=$request->getSession()->get('cardnext.quote_submission');$expected=is_string($storedToken)?$storedToken:'';if($expected!==''&&hash_equals($expected,$token)){try{$submitter->submit($quote,$channel,$request->getLocale());$request->getSession()->remove('cardnext.quote_submission');$this->cart->clear();$mailer->send($quote);return $this->redirectToRoute('cardnext_shop_quote_confirmation',['_locale'=>$request->getLocale(),'number'=>$quote->getNumber()]);}catch(\DomainException){$this->addFlash('error','cardnext.quote.empty');}}}$submission=Uuid::v4()->toRfc4122();$request->getSession()->set('cardnext.quote_submission',$submission);$form->add('_submission',\Symfony\Component\Form\Extension\Core\Type\HiddenType::class,['mapped'=>false,'data'=>$submission]);return $this->render('shop/quote/cart.html.twig',['items'=>$items,'form'=>$form,'currency'=>$channel->getBaseCurrency()?->getCode()]);}
 #[Route('/{_locale}/angebotskorb/hinzufuegen',name:'cardnext_shop_quote_cart_add',methods:['POST'],priority:200)] public function add(Request $r):Response{$this->csrf($r,'quote_add');$ok=$this->cart->add($r->request->getString('variantCode'),$r->request->getInt('quantity',1),$this->channel());$this->addFlash($ok?'success':'error',$ok?'cardnext.quote.added':'cardnext.quote.invalid_item');return $this->redirect($r->headers->get('referer')?:$this->generateUrl('cardnext_shop_quote_cart',['_locale'=>$r->getLocale()]));}
 #[Route('/{_locale}/angebotskorb/aktualisieren',name:'cardnext_shop_quote_cart_update',methods:['POST'],priority:200)] public function update(Request $r):Response{$this->csrf($r,'quote_update');$this->cart->update($r->request->getString('variantCode'),$r->request->getInt('quantity'),$this->channel());return $this->redirectToRoute('cardnext_shop_quote_cart',['_locale'=>$r->getLocale()]);}
 #[Route('/{_locale}/angebotskorb/entfernen',name:'cardnext_shop_quote_cart_remove',methods:['POST'],priority:200)] public function remove(Request $r):Response{$this->csrf($r,'quote_remove');$this->cart->remove($r->request->getString('variantCode'),$this->channel());return $this->redirectToRoute('cardnext_shop_quote_cart',['_locale'=>$r->getLocale()]);}
 #[Route('/{_locale}/angebotskorb/leeren',name:'cardnext_shop_quote_cart_clear',methods:['POST'],priority:200)] public function clear(Request $r):Response{$this->csrf($r,'quote_clear');$this->cart->clear();return $this->redirectToRoute('cardnext_shop_quote_cart',['_locale'=>$r->getLocale()]);}
 #[Route('/{_locale}/angebotsanfrage/{number}/bestaetigung',name:'cardnext_shop_quote_confirmation',requirements:['number'=>'AN-\\d{4}-\\d{5,}'],methods:['GET'],priority:200)] public function confirmation(string $number):Response{return $this->render('shop/quote/confirmation.html.twig',['number'=>$number]);}
 private function channel():ChannelInterface{$channel=$this->channels->getChannel();if(!$channel instanceof ChannelInterface)throw new \LogicException('A core sales channel is required.');return $channel;} private function csrf(Request $r,string $id):void{if(!$this->isCsrfTokenValid($id,$r->request->getString('_token')))throw $this->createAccessDeniedException();}}
