sylius_twig_hooks:
    hooks:
        'sylius_admin.product.create.content.form.side_navigation':
            cardnext_product_data:
                template: 'admin/cardnext/product/side_navigation.html.twig'
                priority: 50

        'sylius_admin.product.update.content.form.side_navigation':
            cardnext_product_data:
                template: 'admin/cardnext/product/side_navigation.html.twig'
                priority: 50

        'sylius_admin.product.create.content.form.sections':
            cardnext_product_data:
                template: 'admin/cardnext/product/section.html.twig'
                priority: 50

        'sylius_admin.product.update.content.form.sections':
            cardnext_product_data:
                template: 'admin/cardnext/product/section.html.twig'
                priority: 50
