sylius_grid:
    grids:
        sylius_admin_product:
            actions:
                main:
                    create:
                        options:
                            links:
                                simple:
                                    label: cardnext.admin.product_create.standard
                                configurable:
                                    label: cardnext.admin.product_create.variant
                                cardnext_configurable:
                                    label: cardnext.admin.product_create.configuration
                                    route: cardnext_admin_product_create_configurable
