liip_imagine:
    loaders:
        sylius_image:
            filesystem:
                data_root:
                    - '%kernel.project_dir%/public/media/image'
                    - '%kernel.project_dir%/public'
    filter_sets:
        cardnext_product_card:
            format: webp
            quality: 85
            filters:
                thumbnail: { size: [600, 600], mode: inset }
