sylius_twig_hooks:
    hooks:
        'sylius_shop.base.header':
            top_bar:
                template: 'shop/layout/header/top_bar.html.twig'
                priority: 300
            content:
                template: 'shop/layout/header/content.html.twig'
                priority: 200
            navbar:
                template: 'shop/layout/header/empty.html.twig'
                priority: 100

        'sylius_shop.base.footer':
            content:
                template: 'shop/layout/footer/content.html.twig'
                priority: 0

        'sylius_admin.product.create.content.form.sections.translations':
            configurator_path:
                template: 'admin/product/form/sections/translations/configurator_path.html.twig'
                priority: 350

        'sylius_admin.product.update.content.form.sections.translations':
            configurator_path:
                template: 'admin/product/form/sections/translations/configurator_path.html.twig'
                priority: 350
