sylius_grid:
    grids:
        sylius_admin_product:
            actions:
                main:
                    create:
                        options:
                            links:
                                simple:
                                    label: cardnext.admin.product_create.standard
                                    route: sylius_admin_product_create_simple
                                configurable:
                                    label: cardnext.admin.product_create.variant
                                    route: sylius_admin_product_create
