cardnext_admin_product_create_configurable:
    path: /%sylius_admin.path_name%/products/new/configurator
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.product::createAction
        _sylius:
            section: admin
            permission: true
            factory:
                method: createConfigurableWithVariant
            form:
                type: Sylius\Bundle\AdminBundle\Form\Type\ProductType
            template: "@SyliusAdmin/shared/crud/create.html.twig"
            redirect: sylius_admin_product_update
            vars:
                route:
                    name: cardnext_admin_product_create_configurable
