<?php
declare(strict_types=1);
namespace App\Controller\Admin;
use App\Entity\Leasing\{LeasingConfiguration,LeasingFactor,LeasingInquiry}; use App\Enum\Leasing\LeasingInquiryStatus; use App\Form\Type\{LeasingConfigurationType,LeasingFactorType}; use Doctrine\ORM\EntityManagerInterface; use Sylius\Component\Core\Model\AdminUserInterface; use Symfony\Bundle\FrameworkBundle\Controller\AbstractController; use Symfony\Component\HttpFoundation\{Request,Response}; use Symfony\Component\Routing\Attribute\Route; use Symfony\Component\Security\Http\Attribute\IsGranted;
#[Route('/admin/cardnext/leasing',name:'cardnext_admin_leasing_')] #[IsGranted(AdminUserInterface::DEFAULT_ADMIN_ROLE)]
final class LeasingAdminController extends AbstractController
{
 public function __construct(private EntityManagerInterface $em){}
 #[Route('/settings',name:'settings',methods:['GET','POST'])] public function settings(Request $r):Response{$c=$this->em->find(LeasingConfiguration::class,1)??new LeasingConfiguration();$f=$this->createForm(LeasingConfigurationType::class,$c)->handleRequest($r);if($f->isSubmitted()&&$f->isValid()){$this->em->persist($c);$this->em->flush();$this->addFlash('success','cardnext.leasing.saved');return $this->redirectToRoute('cardnext_admin_leasing_settings');}return $this->render('admin/cardnext/leasing/settings.html.twig',['form'=>$f]);}
 #[Route('/factors',name:'factor_index',methods:['GET'])] public function factors():Response{return $this->render('admin/cardnext/leasing/factors.html.twig',['factors'=>$this->em->getRepository(LeasingFactor::class)->findBy([],['position'=>'ASC'])]);}
 #[Route('/factors/new',name:'factor_create',methods:['GET','POST'])] #[Route('/factors/{id}/edit',name:'factor_edit',methods:['GET','POST'])] public function factor(Request $r,?LeasingFactor $factor=null):Response{$factor??=new LeasingFactor();$f=$this->createForm(LeasingFactorType::class,$factor)->handleRequest($r);if($f->isSubmitted()&&$f->isValid()){$this->em->persist($factor);$this->em->flush();return $this->redirectToRoute('cardnext_admin_leasing_factor_index');}return $this->render('admin/cardnext/leasing/factor_form.html.twig',['form'=>$f,'factor'=>$factor]);}
 #[Route('/factors/{id}/delete',name:'factor_delete',methods:['POST'])] public function deleteFactor(LeasingFactor $factor,Request $r):Response{if(!$this->isCsrfTokenValid('leasing-factor-'.$factor->getId(),(string)$r->request->get('_token')))throw $this->createAccessDeniedException();$this->em->remove($factor);$this->em->flush();return $this->redirectToRoute('cardnext_admin_leasing_factor_index');}
 #[Route('/inquiries',name:'inquiry_index',methods:['GET'])] public function inquiries(Request $r):Response{$qb=$this->em->getRepository(LeasingInquiry::class)->createQueryBuilder('i')->orderBy('i.createdAt','DESC');if($s=$r->query->get('status'))$qb->andWhere('i.status=:s')->setParameter('s',$s);if($q=trim((string)$r->query->get('q'))) $qb->andWhere('i.inquiryNumber LIKE :q OR i.company LIKE :q OR i.firstName LIKE :q OR i.lastName LIKE :q OR i.email LIKE :q OR i.productNameSnapshot LIKE :q OR i.productCodeSnapshot LIKE :q')->setParameter('q','%'.$q.'%');return $this->render('admin/cardnext/leasing/inquiries.html.twig',['inquiries'=>$qb->getQuery()->getResult(),'statuses'=>LeasingInquiryStatus::cases()]);}
 #[Route('/inquiries/{id}',name:'inquiry_show',methods:['GET','POST'])] public function inquiry(LeasingInquiry $i,Request $r):Response{if($r->isMethod('POST')){if(!$this->isCsrfTokenValid('leasing-inquiry-'.$i->getId(),(string)$r->request->get('_token')))throw $this->createAccessDeniedException();$status=LeasingInquiryStatus::tryFrom((string)$r->request->get('status'));if($status)$i->setStatus($status);$i->setInternalNote(trim((string)$r->request->get('internalNote'))?:null);$this->em->flush();}return $this->render('admin/cardnext/leasing/inquiry.html.twig',['inquiry'=>$i,'statuses'=>LeasingInquiryStatus::cases()]);}
}
