<?php

declare(strict_types=1);
namespace App\Controller\Admin; use App\Entity\Quote\QuoteRequest; use App\Entity\Quote\QuoteRequestHistory; use App\Enum\Quote\QuoteRequestStatus; use Doctrine\ORM\EntityManagerInterface; use Symfony\Bundle\FrameworkBundle\Controller\AbstractController; use Symfony\Component\HttpFoundation\{Request,Response}; use Symfony\Component\Routing\Attribute\Route;
#[Route('/admin/cardnext/quotes',name:'cardnext_admin_quote_')]
final class QuoteAdminController extends AbstractController {public function __construct(private EntityManagerInterface $em){}
 #[Route('',name:'index',methods:['GET'])] public function index(Request $r):Response{$this->denyAccessUnlessGranted('ROLE_ADMINISTRATION_ACCESS');$qb=$this->em->getRepository(QuoteRequest::class)->createQueryBuilder('q')->orderBy('q.createdAt','DESC');if($status=$r->query->get('status'))$qb->andWhere('q.status = :status')->setParameter('status',$status);if($channel=$r->query->get('channel'))$qb->andWhere('q.channelCode = :channel')->setParameter('channel',$channel);return $this->render('admin/cardnext/quote/index.html.twig',['quotes'=>$qb->getQuery()->getResult(),'statuses'=>QuoteRequestStatus::cases()]);}
 #[Route('/{id}',name:'show',requirements:['id'=>'\\d+'],methods:['GET'])] public function show(QuoteRequest $quote):Response{$this->denyAccessUnlessGranted('ROLE_ADMINISTRATION_ACCESS');return $this->render('admin/cardnext/quote/show.html.twig',['quote'=>$quote,'statuses'=>QuoteRequestStatus::cases()]);}
 #[Route('/{id}/status',name:'status',requirements:['id'=>'\\d+'],methods:['POST'])] public function status(QuoteRequest $quote,Request $r):Response{$this->denyAccessUnlessGranted('ROLE_ADMINISTRATION_ACCESS');if(!$this->isCsrfTokenValid('quote_status_'.$quote->getId(),(string)$r->request->get('_token')))throw $this->createAccessDeniedException();$next=QuoteRequestStatus::tryFrom((string)$r->request->get('status'));$old=$quote->getStatus();if(!$next||!$old->canTransitionTo($next))throw $this->createNotFoundException('Invalid quote status transition.');$quote->setStatus($next);$quote->addHistory(new QuoteRequestHistory('status_changed',$old->value,$next->value));$this->em->flush();return $this->redirectToRoute('cardnext_admin_quote_show',['id'=>$quote->getId()]);}}
