<?php
declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Schema\Schema; use Doctrine\Migrations\AbstractMigration;
final class Version20260903190000 extends AbstractMigration { public function getDescription():string{return 'Add channel-aware CMS pages, layouts, structured blocks, menus and redirects';} public function up(Schema $schema):void {
 $o=" DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB";
 $this->addSql("CREATE TABLE cardnext_cms_layout (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(64) NOT NULL, name VARCHAR(255) NOT NULL, renderer VARCHAR(32) NOT NULL, enabled TINYINT(1) NOT NULL, allowed_block_types JSON DEFAULT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', updated_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX UNIQ_CMS_LAYOUT_CODE (code), PRIMARY KEY(id))$o");
 $this->addSql("CREATE TABLE cardnext_cms_page (id INT AUTO_INCREMENT NOT NULL, layout_id INT NOT NULL, code VARCHAR(64) NOT NULL, status VARCHAR(16) NOT NULL, publish_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', unpublish_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', include_in_sitemap TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', updated_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX UNIQ_CMS_PAGE_CODE (code), INDEX IDX_CMS_PAGE_LAYOUT (layout_id), INDEX IDX_CMS_PUBLICATION (status,publish_at,unpublish_at), PRIMARY KEY(id))$o");
 $this->addSql("CREATE TABLE cardnext_cms_page_channel (cms_page_id INT NOT NULL, channel_id INT NOT NULL, INDEX IDX_CMS_PC_PAGE (cms_page_id), INDEX IDX_CMS_PC_CHANNEL (channel_id), PRIMARY KEY(cms_page_id,channel_id))$o");
 $this->addSql("CREATE TABLE cardnext_cms_page_translation (id INT AUTO_INCREMENT NOT NULL, page_id INT NOT NULL, locale VARCHAR(12) NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, lead LONGTEXT DEFAULT NULL, meta_title VARCHAR(255) DEFAULT NULL, meta_description VARCHAR(500) DEFAULT NULL, canonical_url VARCHAR(2048) DEFAULT NULL, robots_index TINYINT(1) NOT NULL, robots_follow TINYINT(1) NOT NULL, og_title VARCHAR(255) DEFAULT NULL, og_description VARCHAR(500) DEFAULT NULL, INDEX IDX_CMS_TRANSLATION_PAGE (page_id), INDEX IDX_CMS_SLUG_LOCALE (slug,locale), UNIQUE INDEX uniq_cms_page_locale (page_id,locale), PRIMARY KEY(id))$o");
 $this->addSql("CREATE TABLE cardnext_cms_block (id INT AUTO_INCREMENT NOT NULL, page_id INT NOT NULL, locale VARCHAR(12) NOT NULL, type VARCHAR(32) NOT NULL, position INT NOT NULL, enabled TINYINT(1) NOT NULL, configuration JSON NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', updated_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX IDX_CMS_BLOCK_PAGE (page_id), INDEX IDX_CMS_BLOCK_RENDER (page_id,locale,enabled,position), PRIMARY KEY(id))$o");
 $this->addSql("CREATE TABLE cardnext_cms_menu (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(64) NOT NULL, name VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_CMS_MENU_CODE (code), PRIMARY KEY(id))$o");
 $this->addSql("CREATE TABLE cardnext_cms_menu_item (id INT AUTO_INCREMENT NOT NULL, menu_id INT NOT NULL, channel_id INT NOT NULL, parent_id INT DEFAULT NULL, page_id INT DEFAULT NULL, locale VARCHAR(12) NOT NULL, label VARCHAR(255) NOT NULL, target_type VARCHAR(8) NOT NULL, route_name VARCHAR(255) DEFAULT NULL, route_parameters JSON DEFAULT NULL, external_url VARCHAR(2048) DEFAULT NULL, position INT NOT NULL, enabled TINYINT(1) NOT NULL, open_in_new_tab TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', updated_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX IDX_CMS_MI_MENU_SCOPE (menu_id,channel_id,locale,enabled,position), INDEX IDX_CMS_MI_PARENT (parent_id), INDEX IDX_CMS_MI_PAGE (page_id), PRIMARY KEY(id))$o");
 $this->addSql("CREATE TABLE cardnext_cms_redirect (id INT AUTO_INCREMENT NOT NULL, channel_id INT NOT NULL, target_page_id INT DEFAULT NULL, locale VARCHAR(12) NOT NULL, source_path VARCHAR(255) NOT NULL, target_path VARCHAR(255) DEFAULT NULL, status_code INT NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX uniq_cms_redirect_scope (channel_id,locale,source_path), INDEX IDX_CMS_REDIRECT_PAGE (target_page_id), PRIMARY KEY(id))$o");
 $this->addSql('ALTER TABLE cardnext_cms_page ADD CONSTRAINT FK_CMS_PAGE_LAYOUT FOREIGN KEY (layout_id) REFERENCES cardnext_cms_layout (id)'); $this->addSql('ALTER TABLE cardnext_cms_page_channel ADD CONSTRAINT FK_CMS_PC_PAGE FOREIGN KEY (cms_page_id) REFERENCES cardnext_cms_page (id) ON DELETE CASCADE, ADD CONSTRAINT FK_CMS_PC_CHANNEL FOREIGN KEY (channel_id) REFERENCES sylius_channel (id) ON DELETE CASCADE'); $this->addSql('ALTER TABLE cardnext_cms_page_translation ADD CONSTRAINT FK_CMS_TRANSLATION_PAGE FOREIGN KEY (page_id) REFERENCES cardnext_cms_page (id) ON DELETE CASCADE'); $this->addSql('ALTER TABLE cardnext_cms_block ADD CONSTRAINT FK_CMS_BLOCK_PAGE FOREIGN KEY (page_id) REFERENCES cardnext_cms_page (id) ON DELETE CASCADE'); $this->addSql('ALTER TABLE cardnext_cms_menu_item ADD CONSTRAINT FK_CMS_MI_MENU FOREIGN KEY (menu_id) REFERENCES cardnext_cms_menu (id) ON DELETE CASCADE, ADD CONSTRAINT FK_CMS_MI_CHANNEL FOREIGN KEY (channel_id) REFERENCES sylius_channel (id) ON DELETE CASCADE, ADD CONSTRAINT FK_CMS_MI_PARENT FOREIGN KEY (parent_id) REFERENCES cardnext_cms_menu_item (id) ON DELETE CASCADE, ADD CONSTRAINT FK_CMS_MI_PAGE FOREIGN KEY (page_id) REFERENCES cardnext_cms_page (id) ON DELETE CASCADE'); $this->addSql('ALTER TABLE cardnext_cms_redirect ADD CONSTRAINT FK_CMS_REDIRECT_CHANNEL FOREIGN KEY (channel_id) REFERENCES sylius_channel (id) ON DELETE CASCADE, ADD CONSTRAINT FK_CMS_REDIRECT_PAGE FOREIGN KEY (target_page_id) REFERENCES cardnext_cms_page (id) ON DELETE CASCADE');
 $this->addSql("INSERT INTO cardnext_cms_layout (code,name,renderer,enabled,allowed_block_types,created_at,updated_at) VALUES ('standard','Standardseite','standard',1,'[\"hero\",\"rich_text\",\"image_text\",\"faq\",\"cta\"]',NOW(),NOW()),('landing','Landingpage','landing',1,'[\"hero\",\"rich_text\",\"image_text\",\"faq\",\"cta\"]',NOW(),NOW()),('service','Service-Seite','service',1,'[\"hero\",\"rich_text\",\"image_text\",\"faq\",\"cta\"]',NOW(),NOW()),('wide','Breite Inhaltsseite','wide',1,'[\"hero\",\"rich_text\",\"image_text\",\"faq\",\"cta\"]',NOW(),NOW())"); $this->addSql("INSERT INTO cardnext_cms_menu (code,name,enabled) VALUES ('utility','Utility navigation',1),('footer_solutions','Footer Lösungen',1),('footer_service','Footer Service',1),('footer_cardnext','Footer Cardnext',1)"); }
 public function down(Schema $schema):void{foreach(['cardnext_cms_redirect','cardnext_cms_menu_item','cardnext_cms_menu','cardnext_cms_block','cardnext_cms_page_translation','cardnext_cms_page_channel','cardnext_cms_page','cardnext_cms_layout'] as $table)$this->addSql('DROP TABLE '.$table);}
}
