<?php
declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Schema\Schema; use Doctrine\Migrations\AbstractMigration;
final class Version20260908120000 extends AbstractMigration
{
 public function getDescription():string{return 'Adds configurable product leasing and immutable leasing inquiries';}
 public function up(Schema $schema):void
 {
  $this->addSql("CREATE TABLE cardnext_leasing_factor (id INT AUTO_INCREMENT NOT NULL, duration_months INT NOT NULL, factor NUMERIC(12, 8) NOT NULL, active TINYINT(1) NOT NULL, active_key INT DEFAULT 1, position INT NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', updated_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX UNIQ_LEASING_DURATION_ACTIVE (duration_months, active_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
  $this->addSql("CREATE TABLE cardnext_leasing_configuration (id INT NOT NULL, default_factor_id INT DEFAULT NULL, enabled TINYINT(1) NOT NULL, provider_name VARCHAR(255) NOT NULL, minimum_net_amount INT NOT NULL, frontend_notice LONGTEXT NOT NULL, cta_text VARCHAR(100) NOT NULL, notification_email VARCHAR(254) DEFAULT NULL, updated_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX IDX_LEASING_DEFAULT (default_factor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
  $this->addSql("CREATE TABLE cardnext_product_leasing_factor (product_id INT NOT NULL, leasing_factor_id INT NOT NULL, INDEX IDX_LEASING_PRODUCT (product_id), INDEX IDX_LEASING_FACTOR (leasing_factor_id), PRIMARY KEY(product_id, leasing_factor_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
  $this->addSql("CREATE TABLE cardnext_leasing_inquiry (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, product_variant_id INT DEFAULT NULL, channel_id INT DEFAULT NULL, inquiry_number VARCHAR(20) NOT NULL, product_name_snapshot VARCHAR(255) NOT NULL, product_code_snapshot VARCHAR(255) NOT NULL, currency_code VARCHAR(3) NOT NULL, net_price INT NOT NULL, leasing_factor_snapshot NUMERIC(12,8) NOT NULL, duration_months INT NOT NULL, calculated_monthly_rate INT NOT NULL, company VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(254) NOT NULL, phone VARCHAR(64) DEFAULT NULL, street VARCHAR(255) DEFAULT NULL, house_number VARCHAR(32) DEFAULT NULL, postal_code VARCHAR(32) NOT NULL, city VARCHAR(128) NOT NULL, country_code VARCHAR(2) DEFAULT NULL, message LONGTEXT DEFAULT NULL, status VARCHAR(32) NOT NULL, internal_note LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', updated_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX UNIQ_LEASING_NUMBER (inquiry_number), INDEX IDX_LEASING_INQUIRY_PRODUCT (product_id), INDEX IDX_LEASING_INQUIRY_VARIANT (product_variant_id), INDEX IDX_LEASING_INQUIRY_CHANNEL (channel_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
  $this->addSql('ALTER TABLE cardnext_leasing_configuration ADD CONSTRAINT FK_LEASING_DEFAULT FOREIGN KEY (default_factor_id) REFERENCES cardnext_leasing_factor (id) ON DELETE SET NULL');$this->addSql('ALTER TABLE cardnext_product_leasing_factor ADD CONSTRAINT FK_LEASING_PRODUCT FOREIGN KEY (product_id) REFERENCES sylius_product (id) ON DELETE CASCADE');$this->addSql('ALTER TABLE cardnext_product_leasing_factor ADD CONSTRAINT FK_LEASING_FACTOR FOREIGN KEY (leasing_factor_id) REFERENCES cardnext_leasing_factor (id) ON DELETE CASCADE');$this->addSql('ALTER TABLE cardnext_leasing_inquiry ADD CONSTRAINT FK_LEASING_INQUIRY_PRODUCT FOREIGN KEY (product_id) REFERENCES sylius_product (id) ON DELETE SET NULL');$this->addSql('ALTER TABLE cardnext_leasing_inquiry ADD CONSTRAINT FK_LEASING_INQUIRY_VARIANT FOREIGN KEY (product_variant_id) REFERENCES sylius_product_variant (id) ON DELETE SET NULL');$this->addSql('ALTER TABLE cardnext_leasing_inquiry ADD CONSTRAINT FK_LEASING_INQUIRY_CHANNEL FOREIGN KEY (channel_id) REFERENCES sylius_channel (id) ON DELETE SET NULL');
  $this->addSql('ALTER TABLE sylius_product ADD leasing_enabled TINYINT(1) DEFAULT 0 NOT NULL, ADD leasing_custom_price INT DEFAULT NULL');
  $this->addSql("INSERT INTO cardnext_leasing_configuration (id,enabled,provider_name,minimum_net_amount,frontend_notice,cta_text,updated_at) VALUES (1,0,'abcfinance / Lease Seven',100000,'Leasingangebot für Gewerbekunden. Vorbehaltlich Bonitätsprüfung und Vertragsannahme durch abcfinance GmbH. Die tatsächlichen Konditionen können abweichen.','Leasing anfragen',NOW())");
 }
 public function down(Schema $schema):void{$this->addSql('ALTER TABLE sylius_product DROP leasing_enabled, DROP leasing_custom_price');$this->addSql('DROP TABLE cardnext_product_leasing_factor');$this->addSql('DROP TABLE cardnext_leasing_inquiry');$this->addSql('DROP TABLE cardnext_leasing_configuration');$this->addSql('DROP TABLE cardnext_leasing_factor');}
}
