<?php
declare(strict_types=1);
namespace App\Entity\Leasing;
use App\Entity\Channel\Channel; use App\Entity\Product\Product; use App\Entity\Product\ProductVariant; use App\Enum\Leasing\LeasingInquiryStatus;
use Doctrine\DBAL\Types\Types; use Doctrine\ORM\Mapping as ORM; use Symfony\Component\Validator\Constraints as Assert;
#[ORM\Entity] #[ORM\Table(name:'cardnext_leasing_inquiry')] #[ORM\HasLifecycleCallbacks]
class LeasingInquiry
{
 #[ORM\Id,ORM\GeneratedValue,ORM\Column] private ?int $id=null;
 #[ORM\Column(name:'inquiry_number',length:20,unique:true)] private string $inquiryNumber='';
 #[ORM\ManyToOne(targetEntity:Product::class)] #[ORM\JoinColumn(nullable:true,onDelete:'SET NULL')] private ?Product $product=null;
 #[ORM\ManyToOne(targetEntity:ProductVariant::class)] #[ORM\JoinColumn(nullable:true,onDelete:'SET NULL')] private ?ProductVariant $productVariant=null;
 #[ORM\ManyToOne(targetEntity:Channel::class)] #[ORM\JoinColumn(nullable:true,onDelete:'SET NULL')] private ?Channel $channel=null;
 #[ORM\Column(length:255)] private string $productNameSnapshot=''; #[ORM\Column(length:255)] private string $productCodeSnapshot='';
 #[ORM\Column(length:3)] private string $currencyCode='EUR'; #[ORM\Column] private int $netPrice=0;
 #[ORM\Column(type:Types::DECIMAL,precision:12,scale:8)] private string $leasingFactorSnapshot='0'; #[ORM\Column] private int $durationMonths=0; #[ORM\Column] private int $calculatedMonthlyRate=0;
 #[Assert\NotBlank,Assert\Length(max:255)] #[ORM\Column(length:255)] private string $company='';
 #[Assert\NotBlank,Assert\Length(max:100)] #[ORM\Column(length:100)] private string $firstName=''; #[Assert\NotBlank,Assert\Length(max:100)] #[ORM\Column(length:100)] private string $lastName='';
 #[Assert\NotBlank,Assert\Email] #[ORM\Column(length:254)] private string $email=''; #[ORM\Column(length:64,nullable:true)] private ?string $phone=null;
 #[ORM\Column(length:255,nullable:true)] private ?string $street=null; #[ORM\Column(length:32,nullable:true)] private ?string $houseNumber=null;
 #[Assert\NotBlank] #[ORM\Column(length:32)] private string $postalCode=''; #[Assert\NotBlank] #[ORM\Column(length:128)] private string $city=''; #[Assert\Country] #[ORM\Column(length:2,nullable:true)] private ?string $countryCode=null;
 #[ORM\Column(type:Types::TEXT,nullable:true)] private ?string $message=null; #[ORM\Column(type:Types::STRING,length:32,enumType:LeasingInquiryStatus::class)] private LeasingInquiryStatus $status=LeasingInquiryStatus::New;
 #[ORM\Column(type:Types::TEXT,nullable:true)] private ?string $internalNote=null; #[ORM\Column(name:'created_at',type:Types::DATETIME_IMMUTABLE)] private \DateTimeImmutable $createdAt; #[ORM\Column(name:'updated_at',type:Types::DATETIME_IMMUTABLE)] private \DateTimeImmutable $updatedAt;
 public function __construct(){ $this->createdAt=$this->updatedAt=new \DateTimeImmutable(); }
 public function getId():?int{return $this->id;} public function getInquiryNumber():string{return $this->inquiryNumber;} public function setInquiryNumber(string $v):void{$this->inquiryNumber=$v;}
 public function getProduct():?Product{return $this->product;} public function setProduct(?Product $v):void{$this->product=$v;} public function getProductVariant():?ProductVariant{return $this->productVariant;} public function setProductVariant(?ProductVariant $v):void{$this->productVariant=$v;} public function getChannel():?Channel{return $this->channel;} public function setChannel(?Channel $v):void{$this->channel=$v;}
 public function getProductNameSnapshot():string{return $this->productNameSnapshot;} public function setProductNameSnapshot(string $v):void{$this->productNameSnapshot=$v;} public function getProductCodeSnapshot():string{return $this->productCodeSnapshot;} public function setProductCodeSnapshot(string $v):void{$this->productCodeSnapshot=$v;}
 public function getCurrencyCode():string{return $this->currencyCode;} public function setCurrencyCode(string $v):void{$this->currencyCode=$v;} public function getNetPrice():int{return $this->netPrice;} public function setNetPrice(int $v):void{$this->netPrice=$v;} public function getLeasingFactorSnapshot():string{return $this->leasingFactorSnapshot;} public function setLeasingFactorSnapshot(string $v):void{$this->leasingFactorSnapshot=$v;} public function getDurationMonths():int{return $this->durationMonths;} public function setDurationMonths(int $v):void{$this->durationMonths=$v;} public function getCalculatedMonthlyRate():int{return $this->calculatedMonthlyRate;} public function setCalculatedMonthlyRate(int $v):void{$this->calculatedMonthlyRate=$v;}
 public function getCompany():string{return $this->company;} public function setCompany(string $v):void{$this->company=$v;} public function getFirstName():string{return $this->firstName;} public function setFirstName(string $v):void{$this->firstName=$v;} public function getLastName():string{return $this->lastName;} public function setLastName(string $v):void{$this->lastName=$v;} public function getEmail():string{return $this->email;} public function setEmail(string $v):void{$this->email=$v;} public function getPhone():?string{return $this->phone;} public function setPhone(?string $v):void{$this->phone=$v;} public function getStreet():?string{return $this->street;} public function setStreet(?string $v):void{$this->street=$v;} public function getHouseNumber():?string{return $this->houseNumber;} public function setHouseNumber(?string $v):void{$this->houseNumber=$v;} public function getPostalCode():string{return $this->postalCode;} public function setPostalCode(string $v):void{$this->postalCode=$v;} public function getCity():string{return $this->city;} public function setCity(string $v):void{$this->city=$v;} public function getCountryCode():?string{return $this->countryCode;} public function setCountryCode(?string $v):void{$this->countryCode=$v;} public function getMessage():?string{return $this->message;} public function setMessage(?string $v):void{$this->message=$v;}
 public function getStatus():LeasingInquiryStatus{return $this->status;} public function setStatus(LeasingInquiryStatus $v):void{$this->status=$v;} public function getInternalNote():?string{return $this->internalNote;} public function setInternalNote(?string $v):void{$this->internalNote=$v;} public function getCreatedAt():\DateTimeImmutable{return $this->createdAt;} public function getUpdatedAt():\DateTimeImmutable{return $this->updatedAt;} #[ORM\PreUpdate] public function touch():void{$this->updatedAt=new \DateTimeImmutable();}
}
