<?php
declare(strict_types=1);
namespace App\Entity\Cms;
use App\Entity\Channel\Channel; use Doctrine\DBAL\Types\Types; use Doctrine\ORM\Mapping as ORM; use Symfony\Component\Validator\Constraints as Assert; use Symfony\Component\Validator\Context\ExecutionContextInterface;
#[ORM\Entity] #[ORM\Table(name:'cardnext_cms_menu_item')] #[ORM\HasLifecycleCallbacks]
class CmsMenuItem { public const PAGE='PAGE'; public const ROUTE='ROUTE'; public const URL='URL'; #[ORM\Id,ORM\GeneratedValue,ORM\Column] private ?int $id=null; #[ORM\ManyToOne(inversedBy:'items')] #[ORM\JoinColumn(name:'menu_id',referencedColumnName:'id',nullable:false,onDelete:'CASCADE')] private ?CmsMenu $menu=null; #[ORM\ManyToOne] #[ORM\JoinColumn(name:'channel_id',referencedColumnName:'id',nullable:false,onDelete:'CASCADE')] private ?Channel $channel=null; #[ORM\Column(length:12)] private string $locale=''; #[ORM\ManyToOne(targetEntity:self::class)] #[ORM\JoinColumn(name:'parent_id',referencedColumnName:'id',onDelete:'CASCADE')] private ?self $parent=null; #[ORM\Column(length:255)] private string $label=''; #[ORM\Column(name:'target_type',length:8)] #[Assert\Choice([self::PAGE,self::ROUTE,self::URL])] private string $targetType=self::PAGE; #[ORM\ManyToOne] #[ORM\JoinColumn(name:'page_id',referencedColumnName:'id',onDelete:'CASCADE')] private ?CmsPage $page=null; #[ORM\Column(name:'route_name',length:255,nullable:true)] private ?string $routeName=null; /** @var array<string,mixed>|null */ #[ORM\Column(name:'route_parameters',type:Types::JSON,nullable:true)] private ?array $routeParameters=null; #[ORM\Column(name:'external_url',length:2048,nullable:true)] private ?string $externalUrl=null; #[ORM\Column] private int $position=0; #[ORM\Column] private bool $enabled=true; #[ORM\Column(name:'open_in_new_tab')] private bool $openInNewTab=false; #[ORM\Column(name:'created_at',type:Types::DATETIME_IMMUTABLE)] private \DateTimeImmutable $createdAt; #[ORM\Column(name:'updated_at',type:Types::DATETIME_IMMUTABLE)] private \DateTimeImmutable $updatedAt;
 public function __construct(){ $this->createdAt=$this->updatedAt=new \DateTimeImmutable();} public function getId():?int{return $this->id;} public function getMenu():?CmsMenu{return $this->menu;} public function setMenu(CmsMenu $v):void{$this->menu=$v;} public function getChannel():?Channel{return $this->channel;} public function setChannel(Channel $v):void{$this->channel=$v;} public function getLocale():string{return $this->locale;} public function setLocale(string $v):void{$this->locale=$v;} public function getParent():?self{return $this->parent;} public function setParent(?self $v):void{$this->parent=$v;} public function getLabel():string{return $this->label;} public function setLabel(string $v):void{$this->label=$v;} public function getTargetType():string{return $this->targetType;} public function setTargetType(string $v):void{$this->targetType=$v;} public function getPage():?CmsPage{return $this->page;} public function setPage(?CmsPage $v):void{$this->page=$v;} public function getRouteName():?string{return $this->routeName;} public function setRouteName(?string $v):void{$this->routeName=$v;} /** @return array<string,mixed> */ public function getRouteParameters():array{return $this->routeParameters??[];} /** @param array<string,mixed>|null $v */ public function setRouteParameters(?array $v):void{$this->routeParameters=$v;} public function getExternalUrl():?string{return $this->externalUrl;} public function setExternalUrl(?string $v):void{$this->externalUrl=$v;} public function getPosition():int{return $this->position;} public function setPosition(int $v):void{$this->position=$v;} public function isEnabled():bool{return $this->enabled;} public function setEnabled(bool $v):void{$this->enabled=$v;} public function isOpenInNewTab():bool{return $this->openInNewTab;} public function setOpenInNewTab(bool $v):void{$this->openInNewTab=$v;} #[ORM\PreUpdate] public function touch():void{$this->updatedAt=new \DateTimeImmutable();}
 #[Assert\Callback] public function validateTarget(ExecutionContextInterface $context):void { $valid=match($this->targetType){self::PAGE=>$this->page!==null&&$this->routeName===null&&$this->externalUrl===null,self::ROUTE=>$this->page===null&&trim((string)$this->routeName)!==''&&$this->externalUrl===null,self::URL=>$this->page===null&&$this->routeName===null&&$this->isSafeUrl($this->externalUrl),default=>false}; if(!$valid)$context->buildViolation('Exactly one safe target matching the target type is required.')->addViolation(); if($this->page && $this->channel && (!$this->page->getChannels()->contains($this->channel)||$this->page->getTranslation($this->locale)===null))$context->buildViolation('The page is unavailable for this channel and locale.')->addViolation(); }
 private function isSafeUrl(?string $url):bool { if(!$url||str_starts_with($url,'//'))return false; if(str_starts_with($url,'/'))return true; return filter_var($url,FILTER_VALIDATE_URL)!==false&&in_array(strtolower((string)parse_url($url,PHP_URL_SCHEME)),['http','https'],true); }
}
