<?php

declare(strict_types=1);
namespace App\Entity\Configurator;
use App\Enum\Configurator\FieldType; use Doctrine\Common\Collections\{ArrayCollection,Collection}; use Doctrine\ORM\Mapping as ORM;
#[ORM\Entity] #[ORM\Table(name:'cardnext_configurator_field')] #[ORM\UniqueConstraint(name:'UNIQ_CN_CFG_FIELD_CODE',columns:['section_id','code'])]
class ConfiguratorField { #[ORM\Id,ORM\GeneratedValue,ORM\Column] private ?int $id=null; #[ORM\ManyToOne(targetEntity:ConfiguratorSection::class,inversedBy:'fields'),ORM\JoinColumn(nullable:false,onDelete:'CASCADE')] private ConfiguratorSection $section; #[ORM\Column(length:100)] private string $code; #[ORM\Column(length:255)] private string $name; #[ORM\Column(type:'text',nullable:true)] private ?string $description=null; #[ORM\Column(type:'text',nullable:true)] private ?string $helpText=null; #[ORM\Column(enumType:FieldType::class,length:30)] private FieldType $type; #[ORM\Column(options:['default'=>false])] private bool $required=false; #[ORM\Column] private int $position=0; #[ORM\Column(options:['default'=>true])] private bool $enabled=true; #[ORM\Column(type:'string',length:64,nullable:true)] private ?string $minimumValue=null; #[ORM\Column(type:'string',length:64,nullable:true)] private ?string $maximumValue=null; #[ORM\Column(type:'string',length:64,nullable:true)] private ?string $step=null; /** @var Collection<int,ConfiguratorValue> */ #[ORM\OneToMany(mappedBy:'field',targetEntity:ConfiguratorValue::class,cascade:['persist'],orphanRemoval:true),ORM\OrderBy(['position'=>'ASC','id'=>'ASC'])] private Collection $values;
 public function __construct(string $code,string $name,FieldType $type){$this->code=$code;$this->name=$name;$this->type=$type;$this->values=new ArrayCollection();} public function getId():?int{return $this->id;} public function setSection(ConfiguratorSection $v):void{$this->section=$v;} public function getSection():ConfiguratorSection{return $this->section;} public function getCode():string{return $this->code;} public function getName():string{return $this->name;} public function getType():FieldType{return $this->type;} public function isRequired():bool{return $this->required;} public function setRequired(bool $v):void{$this->required=$v;} public function isEnabled():bool{return $this->enabled;} public function setEnabled(bool $v):void{$this->enabled=$v;} public function getMinimumValue():?string{return $this->minimumValue;} public function setMinimumValue(?string $v):void{$this->minimumValue=$v;} public function getMaximumValue():?string{return $this->maximumValue;} public function setMaximumValue(?string $v):void{$this->maximumValue=$v;} public function getStep():?string{return $this->step;} public function setStep(?string $v):void{$this->step=$v;} public function setPosition(int $v):void{$this->position=$v;} public function getPosition():int{return $this->position;} /** @return Collection<int,ConfiguratorValue> */ public function getValues():Collection{return $this->values;} public function addValue(ConfiguratorValue $v):void{if(!$this->values->contains($v)){$this->values->add($v);$v->setField($this);}}
}
